#!/bin/bash
#SBATCH --job-name="clust knn dens"
#SBATCH --nodelist=argon-tesla1
#SBATCH --gres=gpu:2
#SBATCH --ntasks=3
#SBATCH --ntasks-per-node=3
#SBATCH --exclusive
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --workdir="/home/pfandedd"

echo "starting"
srun echo `hostname`

cd /data/argon-fs/sgs/pfandedd/DissertationCodeTesla1/SGpp
srun ./argon_job_scripts/argon_tesla1_knn_density_run.sh
