#!/bin/bash
#SBATCH --job-name="clustering experiments"
#SBATCH --nodelist=argon-tesla1
#SBATCH --gres=gpu:2
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.out # STDERR
#SBATCH --workdir="/home/pfandedd"

echo "starting"
srun echo `hostname`

cd /data/argon-fs/sgs/pfandedd/DissertationCodeTesla1/SGpp

git pull
source source_autotunetmp_generic.sh
scons -j20

# auto-tune first
# ./diss_experiments/regression_unified_AutoTuneTMP.sh
# # experiments that depend on auto-tuning results
# ./diss_experiments/regression_unified_AutoTuneTMP_untuned_start.sh
./diss_experiments/regression_unified_AutoTuneTMP_untuned_start_compare_PVN.sh
