#!/bin/bash
#SBATCH --job-name="clustering experiments"
#SBATCH --nodelist=argon-gtx
#SBATCH --gres=gpu:8
#SBATCH --ntasks=9
#SBATCH --ntasks-per-node=9
#SBATCH --exclusive
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --workdir="/home/pfandedd"

echo "starting"
srun echo `hostname`

cd /data/argon-fs/sgs/pfandedd/DissertationCodeGTX/SGpp
source source_autotunetmp_generic.sh
python3 ./argon_job_scripts/tune_clustering.py
