#!/bin/bash
#SBATCH --job-name="regression experiments"
#SBATCH --nodelist=argon-epyc
#SBATCH -p epyc
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.out # STDERR
#SBATCH --workdir="/home/pfandedd"

echo "starting"
srun echo `hostname`

cd /data/argon-fs/sgs/pfandedd/DissertationCodeEpyc/SGpp
source source_autotunetmp_generic.sh
python3 ./diss_experiments/regression_tuning.py
